name: Deploy HRMS API Production

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HRMS_API_PROD_SSH_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -p 777 ${{ secrets.HRMS_API_PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh \
            -vvv \
            -i ~/.ssh/github-actions \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=yes \
            -p 777 \
            ${{ secrets.HRMS_API_PROD_USER }}@${{ secrets.HRMS_API_PROD_HOST }} \
            "echo 'SSH SUCCESS'; whoami; hostname; pwd"
